package mplanet.explorer;

import java.net.*;
import java.io.*;

public class MPlanetQuickView extends javax.swing.JDialog {
    
   
    public MPlanetQuickView(String name) {
        super(new javax.swing.JFrame(), true);
        fileName=name;
		System.out.println(fileName);
        initComponents();
        qView();
    }
    
	public MPlanetQuickView(File f, ObjectOutputStream o, ObjectInputStream i) {
        super(new javax.swing.JFrame(), true);
		file=f;
		os=o;
		is=i;
		fileName=f.toString();
		initComponents();
		
		qViewRemote();

        
    }


	public void qViewRemote(){
		byte[] b=new byte[1024*1024];
		int r=0;
		try{
            os.writeObject("Q");
            os.flush();
            os.writeObject(file);
            os.flush();
			is.readFully(b);
			r=is.readInt();
		}catch(Exception e){System.out.println("QvErr: "+e);}
		
		if(!image())
			jPanel1.add(new javax.swing.JTextArea(new String(b, 0, r)));
		else
			jPanel1.add(new javax.swing.JLabel(new javax.swing.ImageIcon(b)));
			
	}
    
    public void qView(){
               
        if(image())
            jPanel1.add(new javax.swing.JLabel(new javax.swing.ImageIcon(fileName)));
        else
            jPanel1.add(new javax.swing.JTextArea(getFileString()));
    }
    

    
    public String getFileString(){
        byte[] b = new byte[1024*1024];
        int r=0;
        try{
            java.io.FileInputStream fs=new java.io.FileInputStream(fileName);
            r=fs.read(b);
        }catch(Exception e){}
        //System.out.println(new String(b));
        return new String(b, 0, r);
    }
    
    public boolean image(){
        if(fileName.endsWith(".jpg")||fileName.endsWith(".jpeg")||
            fileName.endsWith(".png")||fileName.endsWith(".gif")||
            fileName.endsWith(".JPG")||fileName.endsWith(".JPEG")||
            fileName.endsWith(".PNG")||fileName.endsWith(".GIF"))
                return true;
        else return false;
        
    }
    
    public void setMid(){
        setSize(new java.awt.Dimension(600, 400));
        setLocation((screenSize.width-600)/2,(screenSize.height-400)/2);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
		jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        jButton1.setText("F");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setTitle("");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setToolTipText("null");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setToolTipText("null");
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);


		isFull=false;
        setTitle("MPlanetQuickView - "+fileName);
        screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        jScrollPane1.setCorner(jScrollPane1.LOWER_RIGHT_CORNER, jButton1);
		setMid();


    }//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        if(isFull){
            end();
            setMid();
            setUndecorated(false);
            isFull=false;
            show();
        }
        else{
            end();
            setUndecorated(true);
            setBounds(0, 0, screenSize.width, screenSize.height);
            isFull=true;
            show();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
        
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        end();
    }//GEN-LAST:event_closeDialog
    
    public void end(){
        setVisible(false);
        dispose();
    }

	private ObjectOutputStream os=null;
	private ObjectInputStream is=null;
    private boolean isFull;
    private String fileName;
	private File file;
    private java.awt.Dimension screenSize;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
