
public class Search extends javax.swing.JDialog {
    
    /** Creates new form try1 */
    public Search(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        goButton = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search....");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jScrollPane1.setViewport(jScrollPane1.getViewport());
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 400, 140));

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 160, 30));

        startButton.setText("Start");
        mainPanel.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        stopButton.setText("Stop");
        mainPanel.add(stopButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        goButton.setText("Go There...");
        mainPanel.add(goButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 110));

        pack();
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    
    public void setTheRow(String n,String p){
        
    }
    
    
    public static void main(String args[]) {
        new Search(new javax.swing.JFrame(), true).show();
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goButton;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JButton stopButton;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
    
}
