package mplanet;

import javax.swing.*;
import javax.swing.event.*;
import javax.swing.text.*;
import javax.swing.text.html.*;
import java.io.*;
import java.net.*;
/**
 *
 * @author  Rakz
 */
public class MPlanetHelp extends javax.swing.JFrame {
    
    /** Creates new form MPlanetHelp1 */
    public MPlanetHelp() {
        initComponents();
        myInit();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTabbedPane1 = new javax.swing.JTabbedPane();
        aboutPanel = new javax.swing.JPanel();
        aboutPane = new javax.swing.JEditorPane();
        helpPanel = new javax.swing.JPanel();
        helpPane = new javax.swing.JEditorPane();

        setTitle("MPlaNet - Help");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        aboutPanel.setLayout(new java.awt.BorderLayout());

        aboutPane.setEditable(false);
        aboutPanel.add(aboutPane, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("tab1", aboutPanel);

        helpPanel.setLayout(new java.awt.BorderLayout());

        helpPane.setEditable(false);
        helpPanel.add(helpPane, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("tab2", helpPanel);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        setBounds(100, 5, 400, 500);
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.dispose();
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    
    public void myInit(){
        URL aboutUrl = null;
        URL helpUrl = null;
        String aboutPath = null;
        String helpPath = null;
        
        jTabbedPane1.setTitleAt(0,"About");
        jTabbedPane1.setTitleAt(1,"Help");
        
        try {
            helpPath = "/mplanet/help/index.html";
            helpUrl = getClass().getResource(helpPath);            
        } catch (Exception e) {            
            new MPError("Cannot open help file");
            helpUrl = null;
        }
        
        try {
            aboutPath = "/mplanet/help/about.html";
            aboutUrl = getClass().getResource(aboutPath);            
        } catch (Exception e) {            
            new MPError("Cannot open help file");
            aboutUrl = null;
        }
        
        if(aboutUrl != null) {
            aboutPane.addHyperlinkListener(createHyperLinkListenerForAbout());
            try{
                aboutPane.setPage(aboutUrl);
            }catch(Exception e){               
            }            
            JScrollPane scroller = new JScrollPane();
            JViewport vp = scroller.getViewport();
            vp.add(aboutPane);
            aboutPanel.add(scroller);            
        }
        
        
        if(helpUrl != null) {
            helpPane.addHyperlinkListener(createHyperLinkListenerForHelp());
            try{
                helpPane.setPage(helpUrl);
            }catch(Exception e){               
            }            
            JScrollPane scroller = new JScrollPane();
            JViewport vp = scroller.getViewport();
            vp.add(helpPane);
            helpPanel.add(scroller);            
        }
        
    }
    
    public static void main(String args[]) {
        new MPlanetHelp().show();
    }
    
    
    public HyperlinkListener createHyperLinkListenerForHelp() {
        return new HyperlinkListener() {
            public void hyperlinkUpdate(HyperlinkEvent e) {
                if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
                    if (e instanceof HTMLFrameHyperlinkEvent) {
                        ((HTMLDocument)helpPane.getDocument()).processHTMLFrameHyperlinkEvent(
                        (HTMLFrameHyperlinkEvent)e);
                    } else {
                        try {
                            helpPane.setPage(e.getURL());
                        } catch (IOException ioe) {
                            new MPError("This page cannot be displayed");
                        }
                    }
                }
            }
        };
    }
    
    
    
    public HyperlinkListener createHyperLinkListenerForAbout() {
        return new HyperlinkListener() {
            public void hyperlinkUpdate(HyperlinkEvent e) {
                if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
                    if (e instanceof HTMLFrameHyperlinkEvent) {
                        ((HTMLDocument)aboutPane.getDocument()).processHTMLFrameHyperlinkEvent(
                        (HTMLFrameHyperlinkEvent)e);
                    } else {
                        try {
                            aboutPane.setPage(e.getURL());
                        } catch (IOException ioe) {
                            new MPError("This page cannot be displayed");
                        }
                    }
                }
            }
        };
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JEditorPane aboutPane;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JEditorPane helpPane;
    private javax.swing.JPanel helpPanel;
    // End of variables declaration//GEN-END:variables
    
}
